import type {
  AgentExpertise,
  AgentSummary,
  AttentionScore,
  BoardSimQuestion,
  Brief,
  ClassifierFeature,
  Decision,
  DecisionReplay,
  DeliberationSession,
  DelegationSuggestion,
  Metric,
  PromptRoute,
  RouterRule,
  RouterStats,
  Risk,
  StoryStep,
} from "./types";

export const metrics: Metric[] = [
  { label: "Revenue", value: "$18.4M", delta: "+6.1%", note: "QoQ", trend: [42, 46, 45, 49, 53, 58, 61] },
  { label: "Pipeline", value: "$42.8M", delta: "+3.4%", note: "weighted", trend: [35, 37, 41, 39, 43, 45, 48] },
  { label: "Delivery", value: "84%", delta: "-2.0%", note: "on-time epics", trend: [88, 87, 86, 87, 85, 84, 84] },
  { label: "Customer Health", value: "91", delta: "+1.2", note: "NPS blend", trend: [87, 88, 89, 90, 90, 91, 91] },
  { label: "Reliability", value: "99.94%", delta: "-0.03%", note: "30d SLO", trend: [99, 99, 98, 99, 99, 99, 99] },
  { label: "Hiring", value: "17 open", delta: "+4", note: "critical roles", trend: [8, 10, 11, 12, 13, 16, 17] },
];

export const suggestedPrompts = [
  "What changed this week across the business?",
  "Where is execution slipping against Q3 goals?",
  "What decisions require my attention this week?",
  "Which cross-functional blockers are rising fastest?",
];

export const decisions: Decision[] = [
  {
    id: "hiring-pace",
    title: "Adjust hiring plan for Platform and Security",
    type: "People / Delivery",
    urgency: "High",
    owner: "COO",
    deadline: "Thu",
    framing:
      "Delivery variance is increasing in integration-heavy streams. We need to decide whether to protect margin or reduce execution risk.",
    options: [
      { title: "Maintain current hiring pace", result: "Protects short-term cost profile, increases Q3 slippage probability." },
      { title: "Targeted acceleration in 3 critical roles", result: "Raises short-term hiring cost, reduces integration queue and delivery risk." },
    ],
    recommendation: "Approve targeted acceleration with a 45-day checkpoint on throughput.",
    confidence: 79,
    assumptions: "Onboarding velocity remains under 30 days for critical roles.",
    confidenceHistory14d: [71, 72, 73, 74, 72, 73, 74, 75, 76, 77, 76, 78, 79, 79],
    reversibility: "reversible",
    strongestCaseAgainst: "Accelerating now adds fixed cost before Q3 revenue visibility is confirmed. A miss on two expansion deals would create a margin squeeze that acceleration cannot absorb.",
    missingEvidence: "Q3 pipeline close probability update from CRO; 30-day onboarding throughput data from People team.",
    delegateTo: undefined,
    cabinetComposition: ["COO Agent", "People Agent", "CFO Agent", "Contrarian Agent"],
  },
  {
    id: "enterprise-bundle",
    title: "Prioritize enterprise feature bundle for two key accounts",
    type: "Product / Revenue",
    urgency: "Medium",
    owner: "CPO",
    deadline: "Next week",
    framing: "Two expansion opportunities require timeline commitments that could displace roadmap capacity.",
    options: [
      { title: "Prioritize bundle this quarter", result: "Improves expansion probability, raises mid-market roadmap risk." },
      { title: "Stage delivery across two releases", result: "Balances risk and preserves broader roadmap trust." },
    ],
    recommendation: "Stage delivery with executive sponsor support for enterprise negotiation.",
    confidence: 74,
    assumptions: "Account teams can hold timelines with transparent phased commitments.",
    confidenceHistory14d: [69, 70, 71, 70, 69, 70, 72, 71, 72, 73, 72, 74, 74, 74],
    reversibility: "reversible",
    strongestCaseAgainst: "Staging signals indecision to key accounts. If a competitor moves faster on enterprise features, the staged approach could cost both deals, not just one.",
    missingEvidence: "Account exec assessment of timeline flexibility; current roadmap capacity report from Engineering.",
    delegateTo: "CPO",
    cabinetComposition: ["Product Agent", "CFO Agent", "COO Agent", "Contrarian Agent"],
  },
  {
    id: "sla-recovery",
    title: "Approve SLA recovery investment for Q4",
    type: "Reliability / Cost",
    urgency: "Medium",
    owner: "CTO",
    deadline: "Mon",
    framing: "Incident recurrence risk dropped, but SLO volatility remains above target in one customer segment.",
    options: [
      { title: "Defer investment", result: "Preserves budget now, increases board-facing reliability downside." },
      { title: "Fund scoped reliability package", result: "Stabilizes SLO confidence and reduces churn narrative risk." },
    ],
    recommendation: "Fund scoped package tied to measurable SLO and escalation reduction targets.",
    confidence: 81,
    assumptions: "Ops and Platform can execute without disrupting Q4 milestones.",
    confidenceHistory14d: [74, 74, 75, 76, 77, 76, 78, 79, 78, 79, 80, 80, 81, 81],
    reversibility: "irreversible",
    strongestCaseAgainst: "This investment competes for engineering bandwidth with two already-committed Q4 features. If Platform slippage worsens, we may fund reliability and still fail on delivery.",
    missingEvidence: "CTO bandwidth assessment for Q4; current incident recurrence probability curve.",
    delegateTo: "CTO",
    cabinetComposition: ["CFO Agent", "COO Agent", "Judge Agent", "Contrarian Agent"],
  },
];

export const risks: Risk[] = [
  {
    id: "risk-delivery",
    title: "Platform delivery slip",
    severity: "High",
    confidence: 82,
    owner: "VP Eng",
    horizon: "2-4 weeks",
    relatedDecisionId: "hiring-pace",
    relatedActionLane: "In Progress",
    relatedMeeting: "Exec Staff · Tue 09:00",
    approvalRef: "APR-1027",
    citations: [
      { id: "cit-1", source: "Jira Program Board", updatedMins: 8, relevance: 0.93 },
      { id: "cit-2", source: "Sprint Health Snapshot", updatedMins: 31, relevance: 0.88 },
      { id: "cit-3", source: "Dependency Queue Report", updatedMins: 190, relevance: 0.81 },
    ],
  },
  {
    id: "risk-legal",
    title: "Enterprise legal bottleneck",
    severity: "Medium",
    confidence: 74,
    owner: "GC",
    horizon: "1-2 weeks",
    relatedDecisionId: "enterprise-bundle",
    relatedActionLane: "Waiting",
    relatedMeeting: "Board Prep · Thu 14:00",
    approvalRef: "APR-1032",
    citations: [
      { id: "cit-4", source: "Deal Desk Blockers", updatedMins: 17, relevance: 0.91 },
      { id: "cit-5", source: "Legal SLA Tracker", updatedMins: 73, relevance: 0.86 },
    ],
  },
  {
    id: "risk-reliability",
    title: "SLO volatility in key segment",
    severity: "Medium",
    confidence: 68,
    owner: "CTO",
    horizon: "4-6 weeks",
    relatedDecisionId: "sla-recovery",
    relatedActionLane: "Blocked",
    relatedMeeting: "Reliability Review · Fri 10:30",
    approvalRef: "APR-1038",
    citations: [
      { id: "cit-6", source: "Incident Trends Dashboard", updatedMins: 11, relevance: 0.89 },
      { id: "cit-7", source: "Escalation Burndown", updatedMins: 220, relevance: 0.84 },
    ],
  },
];

export const agents: AgentSummary[] = [
  {
    name: "CFO Agent",
    role: "specialist",
    focus: "Margin pressure and scenario sensitivity.",
    recommendation: "Preserve hiring acceleration but cap non-critical contractor spend.",
    confidence: 84,
    decisionTypes: ["People / Delivery", "Reliability / Cost", "Product / Revenue"],
  },
  {
    name: "COO Agent",
    role: "specialist",
    focus: "Cross-functional execution and blockers.",
    recommendation: "Stand up a 6-week integration strike team with weekly executive review.",
    confidence: 87,
    decisionTypes: ["People / Delivery", "Reliability / Cost"],
  },
  {
    name: "Product Agent",
    role: "specialist",
    focus: "Roadmap tradeoffs and customer outcomes.",
    recommendation: "Stage enterprise features while protecting reliability-critical product areas.",
    confidence: 79,
    decisionTypes: ["Product / Revenue"],
  },
  {
    name: "People Agent",
    role: "specialist",
    focus: "Hiring velocity and org load health.",
    recommendation: "Prioritize senior backend and TPM roles for integration-heavy streams.",
    confidence: 76,
    decisionTypes: ["People / Delivery"],
  },
  {
    name: "Contrarian Agent",
    role: "contrarian",
    focus: "Steelmanning the opposing case and exposing hidden assumptions.",
    recommendation: "The current recommendation underweights pipeline uncertainty. Delay acceleration until Q3 close probability rises above 70%.",
    confidence: 71,
    dissent: "We are pattern-matching to past delivery problems without checking whether this cycle's root cause is actually headcount-driven.",
    decisionTypes: ["People / Delivery", "Product / Revenue", "Reliability / Cost"],
  },
  {
    name: "Moonshot Agent",
    role: "moonshot",
    focus: "High-upside, asymmetric paths the current frame may be missing.",
    recommendation: "Consider a temporary external integration partner to unblock Q3 delivery without permanent headcount — preserves optionality for Q4 restructure.",
    confidence: 58,
    dissent: "The current option set is too binary. There are at least two structural alternatives not yet modeled.",
    decisionTypes: ["People / Delivery", "Product / Revenue"],
  },
  {
    name: "Judge Agent",
    role: "judge",
    focus: "Evidence sufficiency, assumption completeness, and recommendation quality.",
    recommendation: "Current decision readiness is 74/100. Missing: CRO pipeline update and People team onboarding capacity confirmation. Do not commit until both are resolved.",
    confidence: 90,
    dissent: "The recommendation is sound directionally but the evidence packet is thin on Q3 revenue risk. Commit is premature.",
    decisionTypes: ["People / Delivery", "Product / Revenue", "Reliability / Cost"],
    model: "claude-opus-4-6",
    temperament: "Methodical. Demands evidence before endorsing any path.",
  },
  {
    name: "Revenue Agent",
    role: "revenue",
    focus: "Maximize revenue and cash velocity within the next 90 days.",
    recommendation: "Prioritize the two enterprise accounts above all else. Acceleration pays for itself if even one expands. Ship, sell, collect.",
    confidence: 82,
    dissent: "Long-term reliability investment competes with near-term pipeline momentum. Defer it or scope it to zero disruption.",
    decisionTypes: ["Product / Revenue", "People / Delivery"],
    model: "claude-sonnet-4-6",
    temperament: "Aggressive. Gravitational pull toward shipping, selling, and collecting money. Maximize the next 90 days.",
    reasoning: "I want a version customers will pay for in 90 days. Everything else is noise.",
  },
  {
    name: "Compounder Agent",
    role: "compounder",
    focus: "Build compounding advantages across multiple quarters and years.",
    recommendation: "Hiring acceleration is right but the mechanism matters. Build the integration playbook now — that compounds. A one-time headcount bump does not.",
    confidence: 78,
    dissent: "Revenue Agent's 90-day framing trades durable compounding for one-time gains. The real opportunity is the platform layer, not the accounts.",
    decisionTypes: ["People / Delivery", "Product / Revenue", "Reliability / Cost"],
    model: "claude-sonnet-4-6",
    temperament: "Patient. Thinks in quarters and years. Seeks decisions that compound. Often at odds with Revenue Agent on time horizon.",
    reasoning: "What decision made today is still paying off in year three?",
  },
];

export const attentionScore: AttentionScore = {
  score: 74,
  pendingApprovals: 3,
  openDecisions: 8,
  blockedActions: 2,
  staleSources: 4,
  contradictions: 2,
  unresolvedRisks: 3,
};

export const decisionReplays: DecisionReplay[] = [
  {
    id: "replay-1",
    decisionTitle: "Q2: Reliability investment over feature expansion",
    quarter: "Q2",
    systemRecommendation: "Fund reliability recovery to reduce churn risk in enterprise segment.",
    humanChoice: "Accepted recommendation with reduced scope.",
    outcome: "Churn rate dropped 1.8% in enterprise segment. SLO met for 11 of 12 weeks.",
    calibrationHeld: true,
  },
  {
    id: "replay-2",
    decisionTitle: "Q1: Enterprise segment entry timing",
    quarter: "Q1",
    systemRecommendation: "Delay entry by one quarter until Platform stability improves.",
    humanChoice: "Overridden — entered enterprise on schedule with higher account executive support.",
    outcome: "Three accounts landed but two required extended onboarding. Net ARR positive but NPS lower than forecast.",
    calibrationHeld: false,
  },
  {
    id: "replay-3",
    decisionTitle: "Q2: Hiring freeze on non-critical roles",
    quarter: "Q2",
    systemRecommendation: "Freeze non-critical roles to preserve margin through low-visibility period.",
    humanChoice: "Accepted. Freeze held for 6 weeks.",
    outcome: "Margin protected. Integration bottleneck worsened — this contributed to current Q3 delivery risk.",
    calibrationHeld: true,
  },
];

export const boardSimQuestions: BoardSimQuestion[] = [
  {
    id: "bsq-1",
    question: "What is the evidence that accelerating hiring now reduces Q3 delivery risk rather than just increasing cost?",
    weakArea: true,
    suggestedResponse: "Dependency queue data shows 28% growth over two sprints. Targeted roles unblock 3 of 5 integration streams. We have a 45-day checkpoint built in with explicit rollback conditions.",
  },
  {
    id: "bsq-2",
    question: "Why are we committing to reliability investment before we know whether Q3 pipeline closes?",
    weakArea: true,
    suggestedResponse: "The SLA recovery package is scoped and reversible within the quarter. The cost of a reliability failure in the enterprise segment exceeds the investment by a factor of three based on current churn data.",
  },
  {
    id: "bsq-3",
    question: "How are you preventing delivery risk from compounding across both the enterprise bundle and the Platform stream simultaneously?",
    weakArea: false,
    suggestedResponse: "We have staged the enterprise features across two releases. Platform work is isolated to integration streams with the new strike team. These are not competing for the same engineering capacity.",
  },
  {
    id: "bsq-4",
    question: "What does the Contrarian Agent say about the recommendation, and why are you proceeding despite the dissent?",
    weakArea: false,
    suggestedResponse: "Contrarian position is valid on pipeline timing. We are proceeding with a conditional commit: acceleration pauses if Q3 pipeline close probability falls below 65% at the 30-day checkpoint.",
  },
];

export const delegationSuggestions: DelegationSuggestion[] = [
  {
    decisionId: "enterprise-bundle",
    suggestedOwner: "CPO",
    rationale: "This is a product-scoped tradeoff with clear ownership. CEO involvement is high-cost and not required for this reversible decision.",
    contextPackage: ["Enterprise pipeline summary", "Roadmap capacity report", "Account exec timeline flexibility assessment"],
    escalationDeadline: "Next Wed",
  },
  {
    decisionId: "sla-recovery",
    suggestedOwner: "CTO",
    rationale: "Reliability investment is within CTO authority and budget envelope. CEO attention is better directed at the hiring decision this week.",
    contextPackage: ["SLO volatility trend", "Q4 milestone impact analysis", "Incident recurrence probability curve"],
    escalationDeadline: "Mon EOD",
  },
];

// ─── Brief Builder ────────────────────────────────────────────────────────────

export const briefTemplates: Brief[] = [
  {
    id: "brief-hiring",
    title: "Q3 Hiring Acceleration — Platform & Security",
    situation: "Delivery variance is rising in integration-heavy streams. Platform and Security are the critical bottlenecks. We currently have 17 open roles, 4 of which are marked critical.",
    stakes: "If we do not act by EOW, Q3 delivery confidence drops below threshold on two major enterprise commitments. Margin impact of acceleration is $280K over the quarter.",
    constraints: "Decision must be made by Thursday. Budget envelope is fixed at Q3 plan + 5% flex. No contractor uplift — headcount only.",
    keyQuestions: [
      "Does targeted acceleration meaningfully reduce integration queue within 45 days?",
      "Which 3 roles have the highest unblock multiplier?",
      "What is the cost of inaction compared to the cost of acceleration?",
    ],
    additionalContext: "See: Jira Program Board (8 min), Sprint Health Snapshot (31 min), Dependency Queue Report (190 min).",
    createdAt: "Today 07:44",
    valid: true,
    validationErrors: [],
  },
  {
    id: "brief-enterprise",
    title: "Enterprise Feature Bundle Prioritization",
    situation: "Two key accounts require timeline commitments on a feature bundle that will displace roadmap capacity in Q3.",
    stakes: "Combined expansion ARR of $1.8M. Delay or refusal risks losing both accounts to a competitor who has committed Q4 delivery.",
    constraints: "Engineering capacity is fixed. Mid-market roadmap has three committed items that cannot slip. CPO owns final call.",
    keyQuestions: [
      "Can we stage the bundle across two releases without losing account confidence?",
      "What is the true roadmap displacement cost?",
      "Should the CEO be involved or delegate entirely to CPO?",
    ],
    additionalContext: "Account exec notes: timeline has some flexibility if framed as phased delivery with exec sponsor.",
    createdAt: "Yesterday 16:22",
    valid: true,
    validationErrors: [],
  },
];

// ─── Deliberation Session ─────────────────────────────────────────────────────

export const activeDeliberation: DeliberationSession = {
  id: "delib-001",
  briefId: "brief-hiring",
  briefTitle: "Q3 Hiring Acceleration — Platform & Security",
  status: "complete",
  recommendation: "Approve targeted acceleration of 3 critical roles with a 45-day checkpoint. Condition: pause if Q3 pipeline close probability drops below 65% at the 30-day mark.",
  voteTally: {
    "COO Agent": "support",
    "CFO Agent": "conditional",
    "People Agent": "support",
    "Product Agent": "support",
    "Revenue Agent": "support",
    "Compounder Agent": "conditional",
    "Contrarian Agent": "dissent",
    "Moonshot Agent": "dissent",
  },
  constraint: {
    timeLimitMins: 5,
    timeElapsedMins: 5.4,
    dollarBudget: 5.00,
    dollarSpent: 2.47,
    contextLimit: 1_000_000,
    contextUsed: 218_400,
    roundsCompleted: 3,
    maxRounds: 5,
  },
  messages: [
    {
      id: "msg-1",
      from: "CEO Agent",
      to: "all",
      type: "broadcast",
      round: 1,
      content: "Board, we are here to make a call on Q3 hiring acceleration for Platform and Security. The brief is loaded. Three roles are in scope: Senior Backend Engineer, Integration TPM, Security Architect. Delivery variance is at 13% and rising. What is your initial read?",
      tokenCost: 0,
    },
    {
      id: "msg-2",
      from: "COO Agent",
      to: "all",
      type: "response",
      round: 1,
      content: "Clear yes. Dependency queue data is unambiguous — integration wait time grew 28% across two sprints. These three roles unblock five streams. Stand up the strike team now with a 6-week charter.",
      tokenCost: 0.09,
    },
    {
      id: "msg-3",
      from: "CFO Agent",
      to: "all",
      type: "response",
      round: 1,
      content: "Conditional support. $280K is manageable inside the 5% flex envelope but I want a pipeline close probability trigger at 30 days. If CRO signals below 65%, we pause. I will not approve open-ended acceleration into a revenue miss.",
      tokenCost: 0.11,
    },
    {
      id: "msg-4",
      from: "Revenue Agent",
      to: "all",
      type: "response",
      round: 1,
      content: "Support. The enterprise accounts need delivery confidence now. Acceleration buys us the right to commit timelines. Without it, we lose the expansion ARR conversation before it starts. Ship.",
      tokenCost: 0.08,
    },
    {
      id: "msg-5",
      from: "Contrarian Agent",
      to: "all",
      type: "response",
      round: 1,
      content: "Hold on. We are pattern-matching to past delivery problems without confirming this cycle's root cause. Is it actually headcount? Or is it architectural debt in the integration layer that three engineers won't fix? I want the root cause named before we approve.",
      tokenCost: 0.12,
    },
    {
      id: "msg-6",
      from: "Moonshot Agent",
      to: "all",
      type: "response",
      round: 1,
      content: "Three engineers is thinking too small. The integration bottleneck is a platform-level problem. What if we spun out an integration squad as a separate product team with its own charter and funding? That compounds. This doesn't.",
      tokenCost: 0.10,
      hasSvg: true,
    },
    {
      id: "msg-7",
      from: "CEO Agent",
      to: "all",
      type: "broadcast",
      round: 2,
      content: "Noted — Contrarian raises root cause. COO: can you confirm the queue growth is headcount-driven and not architectural? Moonshot: the platform squad idea is interesting but we need a 45-day answer, not a quarter-long restructure. Push further on the conditional case.",
      tokenCost: 0,
    },
    {
      id: "msg-8",
      from: "COO Agent",
      to: "all",
      type: "response",
      round: 2,
      content: "Root cause confirmed: three of five blocked streams are waiting on human review and integration sign-off, not system limits. It is headcount. The architectural debt is real but secondary to this quarter.",
      tokenCost: 0.09,
    },
    {
      id: "msg-9",
      from: "Compounder Agent",
      to: "all",
      type: "response",
      round: 2,
      content: "I can support acceleration if — and only if — we build the integration playbook as part of onboarding. That is the durable piece. One-time headcount without process documentation does not compound. Conditional support, same as CFO.",
      tokenCost: 0.11,
    },
    {
      id: "msg-10",
      from: "CEO Agent",
      to: "all",
      type: "system",
      round: 3,
      content: "Constraint reached: 5.4 minutes elapsed. Budget at $2.47. Final positions — one statement each.",
      tokenCost: 0,
    },
    {
      id: "msg-11",
      from: "Contrarian Agent",
      to: "all",
      type: "closing",
      round: 3,
      content: "COO confirmed the root cause. I withdraw my block. Conditional support — require explicit root cause statement in the action plan so we can test the assumption at the 45-day checkpoint.",
      tokenCost: 0.07,
    },
    {
      id: "msg-12",
      from: "Moonshot Agent",
      to: "all",
      type: "closing",
      round: 3,
      content: "I still dissent. Three engineers does not move the needle on a platform problem. But I acknowledge I cannot name a faster alternative within the quarter. Log my dissent in the memo.",
      tokenCost: 0.06,
    },
  ],
  stances: [
    { agentName: "COO Agent", position: "support", summary: "Root cause confirmed. Strike team now.", closingStatement: "Stand up the 6-week integration strike team. COO owns the weekly executive review.", confidence: 91 },
    { agentName: "CFO Agent", position: "conditional", summary: "Support with pipeline trigger at day 30.", closingStatement: "Approve with condition: pause if pipeline close probability drops below 65% at day 30.", confidence: 84 },
    { agentName: "Revenue Agent", position: "support", summary: "Acceleration buys the enterprise conversation.", closingStatement: "Ship it. Enterprise ARR depends on delivery confidence.", confidence: 86 },
    { agentName: "People Agent", position: "support", summary: "Prioritize senior backend and TPM first.", closingStatement: "Sequence: Security Architect last. Backend and TPM unblock more streams faster.", confidence: 79 },
    { agentName: "Product Agent", position: "support", summary: "Preserves enterprise bundle timeline.", closingStatement: "Acceleration is necessary to protect the staged enterprise delivery commitment.", confidence: 77 },
    { agentName: "Compounder Agent", position: "conditional", summary: "Support if playbook is built during onboarding.", closingStatement: "Conditional: integration playbook must be a deliverable of the onboarding process, not an afterthought.", confidence: 72 },
    { agentName: "Contrarian Agent", position: "conditional", summary: "Root cause confirmed — withdraw block.", closingStatement: "Conditional support. Require root cause hypothesis logged in action plan and tested at checkpoint.", confidence: 68 },
    { agentName: "Moonshot Agent", position: "dissent", summary: "Three engineers does not solve a platform problem.", closingStatement: "I dissent. The real answer is a platform squad. Log this for the Q4 restructure conversation.", confidence: 55 },
  ],
  tensions: [
    {
      id: "t-1",
      between: ["Revenue Agent", "Compounder Agent"],
      description: "Revenue wants acceleration for 90-day enterprise momentum; Compounder insists the mechanism must be process-driven to compound beyond the quarter.",
      resolved: true,
      resolution: "Both accepted conditional support with playbook requirement. Near-term and long-term interests aligned on the integration playbook deliverable.",
    },
    {
      id: "t-2",
      between: ["Moonshot Agent", "COO Agent"],
      description: "Moonshot argues this is a platform-level problem requiring a structural squad; COO confirmed the root cause is headcount-driven and actionable this quarter.",
      resolved: false,
    },
    {
      id: "t-3",
      between: ["CFO Agent", "Revenue Agent"],
      description: "CFO wants a hard pipeline trigger to pause acceleration; Revenue Agent resists any brake on momentum.",
      resolved: true,
      resolution: "CFO's trigger accepted as a condition of support. Revenue Agent agreed it is a reasonable guardrail given pipeline uncertainty.",
    },
  ],
};

// ─── Agent Expertise ──────────────────────────────────────────────────────────

export const agentExpertise: AgentExpertise[] = [
  {
    agentName: "COO Agent",
    tokenCount: 11200,
    allyAgents: ["Revenue Agent", "People Agent"],
    rivalAgents: ["Moonshot Agent"],
    keyPatterns: [
      "Integration bottlenecks almost always resolve to headcount or review gates — never system limits in this stage",
      "Strike teams work best with a single named owner and a fixed charter duration",
      "COO-led weekly review cadences improve action completion rate by ~30%",
    ],
    decisionsBriefed: 14,
    lastUpdated: "Today 08:01",
  },
  {
    agentName: "CFO Agent",
    tokenCount: 9800,
    allyAgents: ["Judge Agent", "Compounder Agent"],
    rivalAgents: ["Moonshot Agent", "Revenue Agent"],
    keyPatterns: [
      "Pipeline close probability is the leading indicator that predicts whether acceleration spend is recovered",
      "5% flex envelope is the maximum I will approve without board visibility",
      "Margin protection matters more in Q3 than in Q4 because Q4 has reforecast flexibility",
    ],
    decisionsBriefed: 14,
    lastUpdated: "Today 08:01",
  },
  {
    agentName: "Revenue Agent",
    tokenCount: 8400,
    allyAgents: ["COO Agent", "Product Agent"],
    rivalAgents: ["Compounder Agent", "CFO Agent"],
    keyPatterns: [
      "90-day prioritization almost always beats multi-quarter framing when revenue is at stake",
      "Enterprise accounts need delivery confidence signals within 2 weeks of a commitment",
      "Revenue Agent and Compounder Agent are at odds on time horizon — expect tension on every brief",
    ],
    decisionsBriefed: 14,
    lastUpdated: "Today 08:01",
  },
  {
    agentName: "Compounder Agent",
    tokenCount: 10100,
    allyAgents: ["CFO Agent", "Judge Agent"],
    rivalAgents: ["Revenue Agent", "Moonshot Agent"],
    keyPatterns: [
      "Revenue Agent's 90-day framing frequently trades durable compounding for one-time gains",
      "The decisions that compound most are process and playbook decisions, not headcount decisions",
      "Ask: what decision made today is still paying off in year three?",
    ],
    decisionsBriefed: 14,
    lastUpdated: "Today 08:01",
  },
  {
    agentName: "Moonshot Agent",
    tokenCount: 6200,
    allyAgents: [],
    rivalAgents: ["COO Agent", "CFO Agent", "Revenue Agent"],
    keyPatterns: [
      "The current option set is almost always too binary — there are structural alternatives not modeled",
      "Moonshot dissents in roughly 60% of briefs. When overruled, log the dissent — it often surfaces in the Q+1 debrief",
      "The right question is: what if we are thinking too small?",
    ],
    decisionsBriefed: 14,
    lastUpdated: "Today 08:01",
  },
  {
    agentName: "Contrarian Agent",
    tokenCount: 7700,
    allyAgents: ["Judge Agent"],
    rivalAgents: ["Revenue Agent", "COO Agent"],
    keyPatterns: [
      "Root cause confirmation is the single most common gap in briefs — always ask for it before approving",
      "Pattern-matching to past problems without confirming the current cycle's cause leads to wrong interventions",
      "Contrarian withdraws blocks when root cause is confirmed — not adversarial for its own sake",
    ],
    decisionsBriefed: 14,
    lastUpdated: "Today 08:01",
  },
];

export const storySteps: StoryStep[] = [
  {
    title: "Step 1: Sense risk",
    description: "Focus the executive view on the highest-confidence risk signal.",
    apply: { section: "signals", riskId: "risk-delivery", decisionId: "hiring-pace", actionLane: "In Progress" },
  },
  {
    title: "Step 2: Frame decision",
    description: "Move directly from risk to linked decision framing and options.",
    apply: { section: "decisions", riskId: "risk-delivery", decisionId: "hiring-pace", actionLane: "In Progress" },
  },
  {
    title: "Step 3: Track execution",
    description: "Check action lane health for the same linked risk.",
    apply: { section: "actions", riskId: "risk-delivery", decisionId: "hiring-pace", actionLane: "In Progress" },
  },
  {
    title: "Step 4: Verify governance",
    description: "Confirm approvals and policy controls tied to this decision.",
    apply: { section: "governance", riskId: "risk-delivery", decisionId: "hiring-pace", actionLane: "In Progress" },
  },
];

// ─── Prompt Routing ────────────────────────────────────────────────────────────

export const promptRoutes: PromptRoute[] = [
  {
    id: "pr-001",
    prompt: "What is the current ARR?",
    complexity: "low",
    classifierConfidence: 0.94,
    model: "haiku",
    tokensIn: 12,
    tokensOut: 38,
    latencyMs: 210,
    costUsd: 0.0001,
    timestamp: "Today 09:12",
  },
  {
    id: "pr-002",
    prompt: "Summarize this week's delivery risks and flag blockers.",
    complexity: "mid",
    classifierConfidence: 0.88,
    model: "sonnet",
    tokensIn: 184,
    tokensOut: 420,
    latencyMs: 890,
    costUsd: 0.0032,
    timestamp: "Today 09:08",
  },
  {
    id: "pr-003",
    prompt: "Given Q3 pipeline close probability at 62%, should we accelerate Platform hiring or hold? Model tradeoffs across 3 scenarios.",
    complexity: "high",
    classifierConfidence: 0.97,
    model: "opus",
    tokensIn: 1840,
    tokensOut: 2100,
    latencyMs: 4200,
    costUsd: 0.089,
    timestamp: "Today 08:55",
  },
  {
    id: "pr-004",
    prompt: "List open actions for the delivery risk.",
    complexity: "low",
    classifierConfidence: 0.91,
    model: "haiku",
    tokensIn: 22,
    tokensOut: 61,
    latencyMs: 195,
    costUsd: 0.0001,
    timestamp: "Today 08:44",
  },
  {
    id: "pr-005",
    prompt: "Draft board prep memo on enterprise segment entry timing with contrarian case included.",
    complexity: "high",
    classifierConfidence: 0.85,
    model: "opus",
    tokensIn: 3200,
    tokensOut: 4100,
    latencyMs: 5800,
    costUsd: 0.142,
    timestamp: "Today 08:31",
  },
  {
    id: "pr-006",
    prompt: "Compare reliability SLA recovery options — cost vs impact.",
    complexity: "mid",
    classifierConfidence: 0.79,
    model: "sonnet",
    tokensIn: 340,
    tokensOut: 610,
    latencyMs: 1100,
    costUsd: 0.0051,
    timestamp: "Today 08:20",
  },
  {
    id: "pr-007",
    prompt: "Who owns the APAC legal dependency review?",
    complexity: "low",
    classifierConfidence: 0.96,
    model: "haiku",
    tokensIn: 14,
    tokensOut: 29,
    latencyMs: 180,
    costUsd: 0.0001,
    timestamp: "Today 08:11",
  },
  {
    id: "pr-008",
    prompt: "Run multi-agent deliberation on Q3 hiring decision with 3 rounds.",
    complexity: "high",
    classifierConfidence: 0.93,
    model: "opus",
    tokensIn: 8400,
    tokensOut: 11200,
    latencyMs: 9100,
    costUsd: 0.391,
    timestamp: "Today 07:44",
    fallback: false,
  },
];

export const routerStats: RouterStats = {
  totalRouted: 847,
  lowPct: 44,
  midPct: 33,
  highPct: 23,
  avgCostSavingsPct: 68,
  driftDetected: true,
  driftNote: "Mid-tier confidence dropped 8 pts over last 200 prompts. Retraining recommended.",
  lastRetrained: "6 days ago",
};

export const routerRules: RouterRule[] = [
  { name: "Token floor", condition: "tokensIn < 50", action: "Route to haiku", active: true },
  { name: "Reasoning depth", condition: "depth_score >= 0.7", action: "Route to opus", active: true },
  { name: "Latency budget", condition: "latencyBudget < 1000ms", action: "Downgrade to haiku if opus > budget", active: true },
  { name: "Cost cap", condition: "costUsd > 0.50 per call", action: "Block and alert", active: true },
  { name: "Domain specificity", condition: "domain_score >= 0.8 AND complexity = mid", action: "Upgrade to opus", active: false },
];

export const classifierFeatures: ClassifierFeature[] = [
  { name: "Token count", weight: 0.82, description: "Raw prompt length — strong low/high signal" },
  { name: "Reasoning depth", weight: 0.91, description: "Nested conditionals, multi-hop logic detection" },
  { name: "Syntactic complexity", weight: 0.74, description: "Sentence structure, clause depth, question type" },
  { name: "Domain specificity", weight: 0.68, description: "Named entity density, domain jargon prevalence" },
  { name: "Output format signal", weight: 0.55, description: "Requests for structured output, tables, code" },
];
